backend:
  name: git-gateway
  branch: master

media_folder: "static/uploads"
public_folder: /uploads

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home"
        name: "index"
        file: "src/pages/index.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Path, name: path, widget: "hidden", default: "/"}
          - {label: The Firm, name: the_firm, widget: object, fields: [
            {label: Heading, name: heading, widget: string}, 
            {label: Text, name: text, widget: string}, 
            {label: Image, name: image, widget: image, required: false}
            ]}
          - {label: Approach, name: approach, widget: object, fields: [
            {label: Heading, name: heading, widget: string}, 
            {label: Text, name: text, widget: string}, 
            {label: Image, name: image, widget: image, required: false}
            ]}
          - {label: Section image one, name: section_image_one, widget: object, fields: [
            {label: Heading, name: heading, widget: string}, 
            {label: Text, name: text, widget: string, required: false}, 
            {label: Image, name: cover_image, widget: image},
            {label: Layout, name: layout, widget: hidden}
            ]}
          - {label: Section image two, name: section_image_two, widget: object, fields: [
            {label: Heading, name: heading, widget: string}, 
            {label: Text, name: text, widget: string, required: false}, 
            {label: Image, name: cover_image, widget: image},
            {label: Layout, name: layout, widget: hidden}
            ]}
          - {label: Section image three, name: section_image_three, widget: object, fields: [
            {label: Heading, name: heading, widget: string}, 
            {label: Text, name: text, widget: string, required: false}, 
            {label: Image, name: cover_image, widget: image},
            {label: Layout, name: layout, widget: hidden}
            ]}
  - name: "partners"
    label: "Partners"
    folder: "src/pages/partners"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: "Position", name: "position", widget: "string" }
      - { label: "Mail", name: "mail", widget: "string" }
      - { label: "Linkedin", name: "linkedin", widget: "string" }
      - { label: "Experience 1", name: "experience_1", widget: "string" }
      - { label: "Experience 2", name: "experience_2", widget: "string" }
      - { label: "Experience 3", name: "experience_3", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "transactions"
    label: "Transactions"
    folder: "src/pages/transactions"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Text", name: "text", widget: "string" }
      - { label: 'Image', name: 'cover_image', widget: 'image' }
      - { label: "Logo", name: "logo", widget: "image" }
      - { label: "Date", name: "date", widget: "date", format: 'MMM Do YY' }
  - name: "industries"
    label: "Industries"
    folder: "src/pages/industries"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Text", name: "text", widget: "string" }
      - { label: 'Image', name: 'cover_image', widget: 'image' }
      - { label: "Background color", name: "bg_color", widget: "hidden" }
      - { label: "Date", name: "date", widget: "date", format: 'MMM Do YY' }